# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jiov3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jiov3
  pod 'Firebase/Messaging'

  target 'jiov3-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'jiov3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'jiov3-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jiov3-tvOS

  

end
